from tf_network.expconfig.std_config import StdDividedConfig
from tf_network.expconfig.runtime_config import RuntimeDividedConfig
from tf_network.expconfig.wider_config import WiderNetworkConfig
from tf_network.expconfig.deeper_config import DeeperNetworkConfig
from tf_network.expconfig.renew_config import RenewNetworkConfig